import React from 'react'

export default function Main() {
  return (
    <div>
      <div>a1</div>
      <div>a2</div>
      <div>a3</div>
      <div>a4</div>
      <div>a5</div>
      <div>a6</div>
      <div>a7</div>
      <div>a8</div>
      <div>a9</div>
      <div>a10</div>
      <div>a11</div>
      <div>a12</div>
      <div>a13</div>
      <div>a14</div>
      <div>a15</div>
      <div>a16</div>
      <div>a17</div>
      <div>a18</div>
      <div>a19</div>
      <div>a20</div>
      <div>a21</div>
      <div>a22</div>
      <div>a23</div>
      <div>a24</div>
      <div>a25</div>
      <div>a26</div>
      <div>a27</div>
      <div>a28</div>
      <div>a29</div>
      <div>a30</div>
      <div>a31</div>
      <div>a32</div>
      <div>a33</div>
      <div>a34</div>
      <div>a35</div>
      <div>a36</div>
      <div>a37</div>
      <div>a38</div>
      <div>a39</div>
      <div>a40</div>
      <div>a41</div>
      <div>a42</div>
      <div>a43</div>
      <div>a44</div>
      <div>a45</div>
      <div>a46</div>
      <div>a47</div>
      <div>a48</div>
      <div>a49</div>
      <div>a50</div>
      <div>a51</div>
      <div>a52</div>
      <div>a53</div>
      <div>a54</div>
      <div>a55</div>
      <div>a56</div>
      <div>a57</div>
      <div>a58</div>
      <div>a59</div>
      <div>a60</div>
      <div>a61</div>
      <div>a62</div>
      <div>a63</div>
      <div>a64</div>
      <div>a65</div>
      <div>a66</div>
      <div>a67</div>
      <div>a68</div>
      <div>a69</div>
      <div>a70</div>
      <div>a71</div>
      <div>a72</div>
      <div>a73</div>
      <div>a74</div>
      <div>a75</div>
      <div>a76</div>
      <div>a77</div>
      <div>a78</div>
      <div>a79</div>
      <div>a80</div>
      <div>a81</div>
      <div>a82</div>
      <div>a83</div>

    </div>
  )
}
